function[CONFIG]=setConfig11(CONFIG)

% congfigID
CONFIG.configID = 11;

% use measurement generated by config XXX
CONFIG.measConfigID = 500;

% measurement generation network
CONFIG.measNetworkID = 'CA-diverge-1';

% model calibration network
CONFIG.caliNetworkID = 'CA-diverge-2';

% parameters
CONFIG.parameterID = 11;

% initial state
CONFIG.initialStateID='INITIAL_STATE_CONFIG-11';

% boundary condition
CONFIG.boundaryConditionID='BOUNDARY_CONDITION_CONFIG-11';

% junction solver
CONFIG.junctionSolverType='multi-lane model';

% running mode
CONFIG.measurement_generation_mode='on';
CONFIG.estimation_mode='off';
CONFIG.particle = 'off';
CONFIG.ABC = 'off';
CONFIG.ABCrejection = 'off';
CONFIG.ABCSMC = 'off';

% data folder (this is the data generated by config xx)
CONFIG.sensorDataFolder = 500;

% save generated testing(sensor) data to the following folder
if (exist (['Result\testingData\config-' num2str(CONFIG.configID)], 'dir') ~= 7)
    mkdir (['Result\testingData\config-' num2str(CONFIG.configID)]);
end
CONFIG.testingDataFolder = (['Result\testingData\config-' num2str(CONFIG.configID) '\']);

% save density evolution related info. to the following folder (LINK, LINK_WITH_SENSOR)
if (exist (['Result\evolutionData\config-' num2str(CONFIG.configID)], 'dir') ~= 7)
    mkdir (['Result\evolutionData\config-' num2str(CONFIG.configID)]);
end
CONFIG.evolutionDataFolder = (['Result\evolutionData\config-' num2str(CONFIG.configID) '\']);
