function[receiving]=receiving(density, vmax, dmax, dc)
receiving = (density >= dc) .* ( vmax*density.*((0<density).*(density<=dc))+...
        (dc*vmax)*(dmax-density)./(dmax-dc).*((dmax>density).*(density>dc))+...
        0.*(density>=dmax)+0.*(density<=0)) + (density < dc).*(vmax*dc);
    
