function[sending]=sending(density, vmax, dmax, dc)
sending = (density>=dc).*(vmax*dc) + (density<dc).* (vmax*density.*((0<density).*(density<=dc))+...
        (dc*vmax)*(dmax-density)./(dmax-dc).*((dmax>density).*(density>dc))+...
        0.*(density>=dmax)+0.*(density<=0));